"""Typed trajectory-measure API and the seven CPU classical implementations."""

from .base import (
    DistanceResult,
    MeasureCapabilities,
    MeasureCapabilityError,
    TrajectoryMeasure,
    TrajectoryView,
    as_trajectory_view,
    projected_points,
)
from .classical import (
    DiscreteFrechetMeasure,
    DTWMeasure,
    EDRMeasure,
    ERPMeasure,
    EuclideanMeasure,
    HausdorffMeasure,
    LCSSMeasure,
)
from .config import (
    BaseMethodConfig,
    ConfigValidationError,
    DiscreteFrechetConfig,
    DTWConfig,
    EDRConfig,
    ERPConfig,
    EuclideanConfig,
    HausdorffConfig,
    LCSSConfig,
)
from .learned import (
    ADAPTER_PROTOCOL_VERSION,
    AdapterRequest,
    AdapterRunResult,
    ExternalAdapter,
    ExternalAdapterError,
    run_external_adapter,
    validate_adapter_output,
)
from .registry import (
    MEASURE_REGISTRY,
    MeasureRegistry,
    MeasureSpec,
    create_measure,
    get_measure,
    registry,
)
from .timing import PairwiseTiming, time_pairwise

__all__ = [
    "BaseMethodConfig",
    "ConfigValidationError",
    "DiscreteFrechetConfig",
    "DiscreteFrechetMeasure",
    "DistanceResult",
    "DTWConfig",
    "DTWMeasure",
    "EDRConfig",
    "EDRMeasure",
    "ERPConfig",
    "ERPMeasure",
    "EuclideanConfig",
    "EuclideanMeasure",
    "HausdorffConfig",
    "HausdorffMeasure",
    "LCSSConfig",
    "LCSSMeasure",
    "MEASURE_REGISTRY",
    "MeasureCapabilities",
    "MeasureCapabilityError",
    "MeasureRegistry",
    "MeasureSpec",
    "PairwiseTiming",
    "TrajectoryMeasure",
    "TrajectoryView",
    "as_trajectory_view",
    "projected_points",
    "create_measure",
    "get_measure",
    "registry",
    "time_pairwise",
    "ADAPTER_PROTOCOL_VERSION",
    "AdapterRequest",
    "AdapterRunResult",
    "ExternalAdapter",
    "ExternalAdapterError",
    "run_external_adapter",
    "validate_adapter_output",
]
